app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#app_index:
#    path: /index
#    defaults: { _controller: AppBundle:Default:index }

rest:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

nelmio_api_doc_bundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
