AppBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
            nullable: false
        email:
            type: string
            length: '255'
            nullable: false
            unique: true
    oneToMany:
        addresses:
            targetEntity: AppBundle\Entity\Address
            mappedBy: user
            cascade: ["persist", "remove"]
            fetch: EAGER

